### ISSUE TITLE
Comments: Make website variable optional

### ISSUE THREAD

**Issue by jchristlieb** [jchristlieb/laravel-blog#4]
Currently posting a comment is only possible if you provide a name, website, and comment. 

@bambamboole: How can I make the website variable optional. The error message I currently receive: "Column website cannot be null".

I guess it has something to do with modifying columns in the migration for comments table.

**Comment by bambamboole** [comment]
You missed the docs :-)
https://laravel.com/docs/5.5/validation#conditionally-adding-rules
Just adding a sometimes as the first validation rule

**Comment by jchristlieb** [comment]
`'website' => 'sometimes|required|url',`

doesn't lead to the desired result. As the server validation keeps saying the website field is required.

**Comment by bambamboole** [comment]
remove required...
only sometimes|url then it only validates for url if it is present in the request

**Comment by jchristlieb** [comment]
nope, doesn't make the trick. It keep's telling me the website format is invalid. 

Probably there is something wrong with my CommentController class and the store method. I'll keep digging :-)

**Comment by bambamboole** [comment]
I think url needs to have http:// or https:// to be valid
