### ISSUE TITLE
Seeding: How to seed the post_tag table?

### ISSUE THREAD

**Issue by jchristlieb** [jchristlieb/laravel-blog#5]
@bambamboole any idea what kind of factory and/or databaseSeeder I need to define to build up relationships among defined tags and available posts? The table accepts *post_id* and *tag_id* variables.

**Comment by bambamboole** [comment]
Just use normal Eloquent in the database seeder to get complex relations seeded:

```
$posts = factory(App\Post::class,30)->create();
$posts->each(function($post){
  $tags = factory(App\Tag::class,2)->create();
  $post->tags()->saveMany($tags);
}
```

I didn't tested it but it should work :-)

**Comment by jchristlieb** [comment]
@bambamboole indeed it does. Thanks for your contribution.
